config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: "home#index"
  resources :categories
  resources :posts do
    resources :comments, only: [:create]
    collection do
      get :filter_by_category
      post :search
    end
  end
  resources :roles
  resources :users

  get "post_pdf/:id" => "pdf_download#export_pdf", as: "post_pdf"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  # nested comment relation setup
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :comments, foreign_key: :parent_id
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = current_user.comments.new(comment_params)
    if !@comment.save
      flash[:notice] = @comment.errors.full_messages.to_sentence
    end

    redirect_to post_path(params[:post_id])
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params
        .require(:comment)
        .permit(:text, :parent_id)
        .merge(post_id: params[:post_id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>" class="bg-light-subtle">
  <div class="bg-primary-subtle p-2 rounded">
    <h6><%= comment.user.name %></h6>
    <p><%= comment.text %></p>
  </div>
  <a href="#" class="comment-form-display">Reply</a>

  <div class="comment-form" style="display: none;">
    <%= render partial: 'comments/form', locals: { post: comment.post, parent: comment } %>
  </div>

  <div class="sub-comment ms-3 mt-2">
    <%= render comment.comments.order(id: :desc) %>
  </div>
</div>

<!--<script>
    document.addEventListener('click', (event) => {
        if (event.target.matches('.comment-form-display')) {
            event.preventDefault();
            const replyLink = event.target;
            const commentForm = replyLink.nextElementSibling;
            commentForm.style.display = commentForm.style.display === 'none' ? 'block' : 'none';
        }
    });
</script>-->

app/views/comments/_form.html.erb
<form action="<%= post_comments_path(post) %>" method="post" class="mt-5">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <% unless parent.nil? %>
  <input type="hidden" name="comment[parent_id]" value="<%=  parent.id  %>">
  <%  end %>

  <div>
    <textarea placeholder="share your important opinion:)" name="comment[text]" class="form-control"></textarea>
  </div>

  <input type="submit" value="Leave a comment" class="btn btn-primary my-4">
</form>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>