config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: "home#index"
  resources :categories
  resources :posts do
    resources :comments, only: [:create]
    collection do
      get :filter_by_category
      post :search
    end
  end
  resources :roles
  resources :users

  get "post_pdf/:id" => "pdf_download#export_pdf", as: "post_pdf"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  settings index: {
    analysis: {
      filter: {
        edge_ngram_filter: {
          type: 'edge_ngram',
          min_gram: 1,
          max_gram: 20
        }
      },
      analyzer: {
        edge_ngram_analyzer: {
          type: 'custom',
          tokenizer: 'standard',
          filter: %w[lowercase edge_ngram_filter]
        }
      }
    }
  } do
    mapping do
      indexes :id, type: 'integer'
      indexes :title, type: 'text', analyzer: 'edge_ngram_analyzer', search_analyzer: 'standard'
      indexes :subtitle, type: 'text', analyzer: 'edge_ngram_analyzer', search_analyzer: 'standard'
      indexes :bich_text, type: 'text', analyzer: 'edge_ngram_analyzer', search_analyzer: 'standard'
      indexes :user_name, type: 'text', analyzer: 'edge_ngram_analyzer', search_analyzer: 'standard', fields: { keyword: { type: 'keyword' } }
      indexes :category_name, type: 'text', analyzer: 'edge_ngram_analyzer', search_analyzer: 'standard', fields: { keyword: { type: 'keyword' } }
    end
  end

  def as_indexed_json(_options = {})
    self.as_json(
      only: %i[id title subtitle bich_text],
      methods: [:user_name, :category_name]
    )
  end

  def user_name
    user&.name
  end

  def category_name
    category&.category
  end

  def self.search(query)
    query_terms = query.split

    response = __elasticsearch__.search(
      {
        query: {
          bool: {
            should: query_terms.map { |term|
              {
                multi_match: {
                  query: term,
                  fields: %w[title subtitle bich_text user_name category_name]
                }
              }
            }
          }
        }
      }
    )

    # Extract the source documents from the hits
    response.records.to_a.map(&:as_indexed_json)
  end

  # Create the Elasticsearch index if it doesn't exist
  Post.__elasticsearch__.create_index! unless Post.__elasticsearch__.index_exists?
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @categories = Category.all
    @posts = Post.paginate(page: params[:page], per_page: 9)
  end

  # GET /posts/1 or /posts/1.json
  def show
    if params[:id] == "filter_by_category"
      # Handle the case when the ID is "filter_by_category"
      # Redirect or render a different view
      redirect_to posts_path, notice: "Invalid post ID"
    else
      @post = Post.find(params[:id])
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  def filter_by_category
    category_id = params[:category_id]
    if category_id.present?
      @category = Category.find(category_id)
      @posts = @category.posts.paginate(page: params[:page], per_page: 5)
    else
      @posts = Post.paginate(page: params[:page], per_page: 5)
    end
    @categories = Category.all

    respond_to do |format|
      format.html { render :index }
      format.js { render :index }
    end
  end


  def search
    @posts = Post.search(params[:q])

    respond_to do |format|
      format.json { render json: @posts }
    end
  end


  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.category = Category.find(params[:post][:category_id])

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :subtitle, :bich_text, :user_id, :comments, :category_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :subtitle, class: "form-label" %>
    <%= form.text_field :subtitle, class: "form-control"  %>
  </div>

  <div class="mb-3">
    <%= form.label :bich_text, class: "form-label" %>
    <%= form.text_area :bich_text, class: "form-control" %>
  </div>

  <div class="d-none">
    <%= form.label :user_id, class: "form-label" %>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="mb-3">
    <%= form.label :category_id, "Category", class: "form-label" %>
    <%= form.select :category_id, Category.pluck(:category, :id), { prompt: "Select category" }, { class: "form-select" } %>
  </div>

  <div>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Subtitle:</strong>
    <%= post.subtitle %>
  </p>

  <p>
    <strong>Bich text:</strong>
    <%= post.bich_text %>
  </p>

  <p>
    <strong>User:</strong>
    <%= post.user_id %>
  </p>

  <p>
    <strong>Comments:</strong>
    <%= post.comments %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= post.category %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<% unless current_user %>
<div class="p-3 mb-2 bg-danger text-white">
  You must be logged in to create new post
      </div>
<% end %>

<div class="d-flex flex-wrap align-items-center" style="gap: 1rem">
  <div>
    <% if current_user %>
      <%= link_to "Share your knowledge", new_post_path, class: "btn btn-primary" %>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>
    <% end %>
  </div>

  <%= form_tag filter_by_category_posts_path, method: :get, class: "d-flex" do %>
    <%= select_tag :category_id, options_from_collection_for_select(@categories, :id, :category, params[:category_id]), include_blank: 'All Categories', class: "form-select" %>
    <%= submit_tag 'Filter', data: { disable_with: 'Filtering...' }, remote: true, class: "btn btn-primary m-2" %>
  <% end %>
</div>


<div class="row justify-content-start" id="posts">
  <% @posts.each do |post| %>
    <div class="col-md-3 my-2">
      <div class="card">
        <img src="/assets/bob.png" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title"><%= post.title %></h5>
          <h6 class="card-subtitle mb-2 text-body-secondary"><%= post.subtitle %>(<%= Category.find(post.category_id).category %>)</h6>
          <p class="card-text"><%= post.bich_text %></p>
          <p class="card-text">by: <%= User.find(post.user_id).name %></p>
          <p class="card-text">total Comments: <%= post.comments.size %></p>
          <%= link_to "Show this post", post, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= will_paginate @posts %>

<style>
    .pagination a, .pagination em, .pagination span.current, .pagination span.gap, .pagination span {
        float: left;
        padding: 0 14px;
        line-height: 38px;
        text-decoration: none;
        background-color: white;
        border: 1px solid #DDD;
        border-left-width: 0;
    }

    .pagination {
        border-left: 1px solid #ddd;
    }
    .first{
        padding : 0;
        float: none;
        border: none;
    }

    .previous_page {
        padding : 0;
        float: none;
        border: none;
    }

    .page{
        padding : 0;
        float: none;
        border: none;
    }
    .next{
        padding : 0;
        float: none;
        border: none;
    }

    .last{
        padding : 0;
        float: none;
        border: none;
    }

</style>

app/views/posts/new.html.erb
<h2>Create post</h2>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%#= render @post %>

<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="/assets/bob.png" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= @post.title %></h5>
        <h6 class="card-subtitle mb-2 text-body-secondary"><%= @post.subtitle %></h6>
        <p class="card-text"><%= @post.bich_text %></p>
        <p class="card-text">by: <%= User.find(@post.user_id).name %></p>
        <%= link_to "Download PDF report", post_pdf_path, class: "btn btn-primary"%>
      </div>
    </div>
  </div>
</div>

<h4>Comments</h4>
<p>
  <%= render @post.comments.where(parent_id: nil).includes(:user).order(id: :desc) %>
</p>

<% if current_user %>
  <%= render partial: 'comments/form', locals: { post: @post, parent: nil } %>
<% else %>
  <%= link_to "You must be logged in to comment", new_user_session_path, class: "btn btn-danger" %>
<% end %>

<div class="d-flex my-3 flex-wrap" style="gap: 1rem">
  <%= link_to "Back to posts", posts_path, class:"btn btn-info"%>
  <% if User.find(@post.user_id) == current_user %>
    <%= link_to "Edit this post", edit_post_path(@post), class:"btn btn-warning" %>
    <%= button_to "Destroy this post", @post, method: :delete, class:"btn btn-danger" %>
  <% end %>
</div>